enyo.depends(
	"$lib/extra/analyzer",
	"$lib/fu",
	"showdown-v0.9/compressed/showdown.js",
	"collapsing",
	"Doc.js",
	"InfoDb.js",
	"Formatlets.js",
	"Formatter.js",
	"Formatter2.js",
	"App.js",
	"css/app.css",
	"css/doc.css",
	"css/format.css"
);
